# Generated by Django 5.0.7 on 2024-09-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_chattoken_grouptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uuid_name', models.CharField(max_length=100)),
                ('uuid_id', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
