# Generated by Django 5.0.7 on 2024-09-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_users_uuid_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatToken',
            new_name='ChatData',
        ),
    ]
