# Generated by Django 5.0.7 on 2024-09-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_chattoken_chatdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdata',
            name='Token',
        ),
        migrations.AddField(
            model_name='chatdata',
            name='receiver',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='sender',
            field=models.CharField(default='', max_length=200),
        ),
    ]
