# Generated by Django 5.0.7 on 2024-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_chatdata_token_chatdata_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
