# Generated by Django 5.0.7 on 2024-09-30 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_chatdata_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('Token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GroupToken',
        ),
    ]
