# Generated by Django 5.0.7 on 2024-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_personaltoken_delete_grouptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
