# Generated by Django 5.0.7 on 2024-10-03 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_grouptoken_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(default='', max_length=100)),
                ('groupname', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
