# Generated by Django 5.0.7 on 2024-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptoken',
            name='groupname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
