# Generated by Django 5.0.7 on 2024-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_grouptoken_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_uuid',
            field=models.CharField(max_length=255),
        ),
    ]
