# Generated by Django 5.0.7 on 2024-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_usergroup_groupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
