# Generated by Django 5.0.7 on 2024-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_groupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdata',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
