# Generated by Django 5.0.7 on 2024-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_groupdata_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='grouptoken',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
